# Generated by Django 4.1.5 on 2023-01-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='is_hukumat',
            field=models.BooleanField(default=False),
        ),
    ]
