# Generated by Django 4.1.5 on 2023-01-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_role_user_is_hukumat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_hukumat',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Hukumat', 'Hukumat'), ('Rais', 'Rais'), ('Hokim yordamchisi', 'Hokim yordamchisi')], default='Hukumat', max_length=200),
        ),
    ]
