# Generated by Django 4.1.5 on 2023-01-08 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('users', '0003_remove_user_is_hukumat_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mahalla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='main.mahalla'),
        ),
        migrations.AddField(
            model_name='user',
            name='tuman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='main.tuman'),
        ),
    ]
