# Generated by Django 4.1.5 on 2023-01-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_mahalla_user_tuman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Hukumat', 'Hukumat'), ('Kadastr', 'Kadastr'), ('Rais', 'Rais'), ('Hokim yordamchisi', 'Hokim yordamchisi')], default='Hukumat', max_length=200),
        ),
    ]
