# Generated by Django 4.1.5 on 2023-01-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Hukumat', 'Hukumat'), ('Kadastr', 'Kadastr'), ('Rais', 'Rais'), ('Hokim yordamchisi', 'Hokim yordamchisi')], max_length=200, null=True),
        ),
    ]
