# Generated by Django 4.1.5 on 2023-01-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Nazoratchi', 'Nazoratchi'), ('Hokimiyat', 'Hokimiyat'), ('Kadastr', 'Kadastr'), ('Qurilish', 'Qurilish'), ('Rais', 'Rais'), ('Hokim yordamchisi', 'Hokim yordamchisi')], max_length=200, null=True),
        ),
    ]
