# Generated by Django 4.1.5 on 2023-01-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_requestmodel_delete_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='context',
            field=models.TextField(default='text', verbose_name='Text contexti'),
            preserve_default=False,
        ),
    ]
