# Generated by Django 4.1.5 on 2023-01-16 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_requestmodel_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmodel',
            name='receiver',
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='hokimiyat_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_as_hokimiyat_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='kadastr_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_as_kadastr_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='qurilish_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_as_qurilish_receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
