# Generated by Django 4.1.5 on 2023-01-16 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_remove_requestmodel_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_as_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
