# Generated by Django 4.1.5 on 2023-02-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_notificationcta_cta_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Request', 'verbose_name_plural': 'Requests'},
        ),
    ]
