# Generated by Django 4.1.5 on 2023-03-03 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_requestmodel_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmodel',
            name='location',
        ),
    ]
