# Generated by Django 4.1.5 on 2023-03-28 16:24

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_requestmodel_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestmodel',
            options={'ordering': ['-created_at'], 'verbose_name': "So'rovnoma", 'verbose_name_plural': "So'rovnomalar"},
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=None, max_length=63),
            preserve_default=False,
        ),
    ]
