# Generated by Django 4.1.5 on 2023-03-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_requestmodel_options_requestmodel_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmodel',
            name='location',
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='location_latitude',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='location_longitude',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
