# Generated by Django 4.1.5 on 2023-03-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_requestmodel_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='location_latitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='location_longitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
