# Generated by Django 4.1.5 on 2023-03-30 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_requestmodel_location_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmodel',
            name='location_latitude',
        ),
        migrations.RemoveField(
            model_name='requestmodel',
            name='location_longitude',
        ),
    ]
