# Generated by Django 4.1.5 on 2023-04-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_requestmodel_location_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='qonun_buzarlik_holati',
            field=models.CharField(choices=[("O'zboshimcha", "O'zboshimcha"), ('Orqtiqcha', 'Ortiqcha maydon'), ('Normaga zid', 'Normaga zid'), ('Qalbaki hujjat', 'Qalbaki hujjat'), ('Boshqa', 'Boshqa qonun buzilish holati')], default='Boshqa', max_length=200),
        ),
    ]
