# Generated by Django 4.1.5 on 2023-04-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_requestmodel_qonun_buzarlik_holati'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmodel',
            name='qonun_buzarlik_holati',
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='taxminiy_qonun_buzarlik_holati',
            field=models.CharField(choices=[("O'zboshimcha", "O'zboshimcha"), ('Orqtiqcha', 'Ortiqcha maydon'), ('Normaga zid', 'Normaga zid'), ('Qalbaki hujjat', 'Qalbaki hujjat'), ('Boshqa qonun buzilish holati', 'Boshqa qonun buzilish holati')], default='Boshqa qonun buzilish holati', max_length=200),
        ),
    ]
