# Generated by Django 4.1.5 on 2023-04-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_requestmodel_qonun_buzarlik_holati_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='taxminiy_qonun_buzarlik_holati',
            field=models.CharField(choices=[("Yerni o'zboshimchalik bilan egallab, noqonuniy qurilish ishlarini amalga oshirmoqda", "`Yerni o'zboshimchalik bilan egallab, noqonuniy qurilish ishlarini amalga oshirmoqda."), ('Huquqiy hujjatda belgilangandan ortiq maydonda qurilish ishlarini amalga oshirmoqda', 'Huquqiy hujjatda belgilangandan ortiq maydonda qurilish ishlarini amalga oshirmoqda.'), ('Qurilish ishlari shaharsozlik norma va qurilish me’yoriy hujjatlariga zid ravishda amalga oshirilmoqda', 'Qurilish ishlari shaharsozlik norma va qurilish me’yoriy hujjatlariga zid ravishda amalga oshirilmoqda'), ('Qalbaki hujjatlar asosida noqonuniy qurilish ishlar amalga oshirilmoqda', 'Qalbaki hujjatlar asosida noqonuniy qurilish ishlar amalga oshirilmoqda'), ('Boshqa qonun buzilish holati', 'Boshqa qonun buzilish holati')], default='Boshqa qonun buzilish holati', max_length=200),
        ),
    ]
