# Generated by Django 4.1.5 on 2023-01-12 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_requestmodel_delete_request'),
        ('hukumat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='main.requestmodel'),
            preserve_default=False,
        ),
    ]
