# Generated by Django 4.1.5 on 2023-01-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hukumat', '0004_alter_response_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='extra_file',
            field=models.FileField(blank=True, null=True, upload_to='qoshimchalar/'),
        ),
    ]
