# Generated by Django 4.1.5 on 2023-01-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hukumat', '0005_response_extra_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='is_kech',
            field=models.BooleanField(default=False),
        ),
    ]
