# Generated by Django 4.1.5 on 2023-02-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hukumat', '0007_rename_is_kech_response_is_late'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='is_certified',
            field=models.BooleanField(default=False, help_text='Bu javob tasdiqlanganmi?'),
        ),
    ]
