# Generated by Django 4.1.5 on 2023-02-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hukumat', '0008_response_is_certified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='is_certified',
            field=models.BooleanField(default=False, help_text='Bu javob tasdiqlanganmi?', verbose_name='Tasdiqlangan'),
        ),
    ]
