# Generated by Django 4.1.5 on 2023-03-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hukumat', '0009_alter_response_is_certified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='is_certified',
            field=models.BooleanField(default=False, help_text='Bu javob tasdiqlanganmi?*', verbose_name='Tasdiqlangan'),
        ),
    ]
