# Generated by Django 4.1.5 on 2023-03-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hukumat', '0010_alter_response_is_certified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'verbose_name': 'Javob', 'verbose_name_plural': 'Javoblar'},
        ),
    ]
